[project]
name = "verse-nnenum-int"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "gokulp01", email = "gokulgns@gmail.com"},
]
dependencies = []
requires-python = "==3.10.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false
